Update CodeFirstSync.yml

diff --git a/.github/workflows/CodeFirstSync.yml b/.github/workflows/CodeFirstSync.yml
--- a/.github/workflows/CodeFirstSync.yml
+++ b/.github/workflows/CodeFirstSync.yml
@@ -24,13 +24,27 @@ jobs:
       - name: Generate Swagger file
         run: npm run swagger  # Adjust this to your Swagger file generation command
 
+      - name: Debug Environment Variables
+        run: |
+         echo "SwaggerHub Owner: ${{ env.SWAGGERHUB_OWNER }}"
+         echo "SwaggerHub API: ${{ env.SWAGGERHUB_API }}"
+         echo "Swagger file path: docs/swagger.json"
+         ls -l docs/swagger.json  # To check if the file exists
+
       - name: Upload Swagger to SwaggerHub
         env:
           SWAGGERHUB_API_KEY: ${{ secrets.SWAGGERHUB_API_KEY }}
           SWAGGERHUB_OWNER: ${{ secrets.SWAGGERHUB_OWNER }}
           SWAGGERHUB_API: ${{ secrets.SWAGGERHUB_API }}
         run: |
-          curl -X POST "https://api.swaggerhub.com/apis/${{ env.SWAGGERHUB_OWNER }}/${{ env.SWAGGERHUB_API }}" \
-          -H "Authorization: ${{ env.SWAGGERHUB_API_KEY }}" \
-          -H "Content-Type: application/json" \
-          --data-binary @docs/swagger.json
+          SWAGGER_FILE=docs/swagger.json
+          if [ -f "$SWAGGER_FILE" ]; then
+            curl -X POST "https://api.swaggerhub.com/apis/${{ env.SWAGGERHUB_OWNER }}/${{ env.SWAGGERHUB_API }}" \
+            -H "Authorization: ${{ env.SWAGGERHUB_API_KEY }}" \
+            -H "Content-Type: application/json" \
+            --data-binary @$SWAGGER_FILE
+          else
+            echo "Swagger file not found: $SWAGGER_FILE
+            exit 1
+          fi
+      
